// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZPjxqPrES7sK9DTF5gSEP5aRQ1ss-fQ',
    appId: '1:217643332600:web:a375b8a687add9839c1c0d',
    messagingSenderId: '217643332600',
    projectId: 'task-manager-faraz',
    authDomain: 'task-manager-faraz.firebaseapp.com',
    storageBucket: 'task-manager-faraz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS0rEOpiXgT3trNm6Yzd1LQC_0OT-RqaE',
    appId: '1:217643332600:android:d4069bb62df4057b9c1c0d',
    messagingSenderId: '217643332600',
    projectId: 'task-manager-faraz',
    storageBucket: 'task-manager-faraz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMAaNDANtfB7ZK56CjU5iM-hW8IMjoQQ',
    appId: '1:217643332600:ios:903c8be3dc86ab3d9c1c0d',
    messagingSenderId: '217643332600',
    projectId: 'task-manager-faraz',
    storageBucket: 'task-manager-faraz.firebasestorage.app',
    androidClientId: '217643332600-q44nk41qmniahfqvgh2tfg4d4cchbpte.apps.googleusercontent.com',
    iosClientId: '217643332600-4dt8qmi3c6a5rqf8ksa7gmmgsolpj796.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiMAaNDANtfB7ZK56CjU5iM-hW8IMjoQQ',
    appId: '1:217643332600:ios:903c8be3dc86ab3d9c1c0d',
    messagingSenderId: '217643332600',
    projectId: 'task-manager-faraz',
    storageBucket: 'task-manager-faraz.firebasestorage.app',
    androidClientId: '217643332600-q44nk41qmniahfqvgh2tfg4d4cchbpte.apps.googleusercontent.com',
    iosClientId: '217643332600-4dt8qmi3c6a5rqf8ksa7gmmgsolpj796.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ZPjxqPrES7sK9DTF5gSEP5aRQ1ss-fQ',
    appId: '1:217643332600:web:308bbaebb0aa289d9c1c0d',
    messagingSenderId: '217643332600',
    projectId: 'task-manager-faraz',
    authDomain: 'task-manager-faraz.firebaseapp.com',
    storageBucket: 'task-manager-faraz.firebasestorage.app',
  );
}
